bases:
  - ../../base

patches:
  - triggers.yaml
  
patchesStrategicMerge:
  - env.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/ssuganth-stage/sampledemo-api
    newTag: stage
