apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
namespace: ssuganth-stage
metadata:
  name: demoapi-dc
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        from:
          kind: ImageStreamTag
          namespace: "ssuganth-stage"
          name: "sampledemo-api:stage"