apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: demoapi-dc
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        from:
          kind: ImageStreamTag
          namespace: "ssuganth-test"
          name: "sampledemo-api:test"