name: GitHub Actions Demo
on:
  push:
    branches: main
  release:
    types: published
env:
  version: 'unmanaged'
  
jobs:
  job1:
    name: Set Version
    runs-on: ubuntu-latest
    steps:
      - name: push condititon
        if: ${{ github.event_name == 'push' }}     
        run: |
            echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            echo "version=managed" >> $GITHUB_ENV
      
      - name: release condition
        if: ${{ github.event_name == 'release' }}
        run: |
            echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    
      - name: print env variable
        run: |
            echo "image version is ${{ env.version }}"
            echo "::set-output name=finalVersion::${{ env.version }}"
  
  job2:
    name: Print Version
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - name: print env variable
        run: |
            echo "image version is ${{ needs.job1.outputs.finalVersion }}"
      
    
    
