name: GitHub Actions Demo
on:
  push:
    branches: main
  release:
    types: published
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: condition 1
      if: ${{ github.event_name == 'push' }}
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      env:
        version: unmanaged
      
    - name: condition 2
      if: ${{ github.event_name == 'published' }}
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      env: 
        version: V1.0
    
    - name: print env variable
      run: echo "image version is ${{ env.version }} "
    
