name: GitHub Actions Demo
on:
  push:
    branches: main
  release:
    types: published
env:
  version: 'unmanaged'
  
jobs:
  job1:
    name: Set Version
    runs-on: ubuntu-latest
    steps:
      - name: condition 1
        if: ${{ github.event_name == 'push' }}     
        run: |
            echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            echo "version=managed" >> $GITHUB_ENV
      
      - name: condition 2
        if: ${{ github.event_name == 'release' }}
        run: |
            echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    
      - name: print env variable
        run: |
            echo "image version is ${{ env.version }}"
  
  job2:
    name: Print Version
    runs-on: ubuntu-latest
    steps:
      - name: print env variable
        run: |
            echo "image version is ${{ env.version }}"
      
    
    
