name: Deployment Trigger workflow and Push to Openshift Registry

on:        
    workflow_dispatch:
        inputs:
            environment:
                description: 'Release Environment'     
                required: true
                default: 'dev'
            version:
                description: 'Release Version'
                required: true
jobs:
  build-sample-api:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2
        
      - name: Hello world action step
        uses: actions/GitHubActions_POC@master
        with:
            who-to-greet: 'Suganth'
    
      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com
          username: ssuganth
          password: sha256~t8ZTFHwtTtooiX6eDRavBP6-0q0BCARLVxGvAw8t4QA

      - name: Build and push
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: .
          IMAGE: default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com/ssuganth-dev/sampledemo-api:${{ github.event.inputs.environment }}
          VERIMAGE: default-route-openshift-image-registry.apps.sandbox.x8i5.p1.openshiftapps.com/ssuganth-dev/sampledemo-api:${{ github.event.inputs.version }}
          RuntimeEnv: ${{ github.event.inputs.environment }}
        run: |
          docker build \
            --build-arg ASPNETCORE_ENVIRONMENT=Development \
            --tag ${IMAGE} \
            --tag ${VERIMAGE} \
            ${CONTEXT}
            docker push ${IMAGE}
            docker push ${VERIMAGE}
