name: OC POD Label SandBox

on:        
    workflow_dispatch:
        inputs:
            environment:
                description: 'Release Environment'     
                required: true
                default: 'dev'
jobs:
  oc-poc:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.environment }}
    outputs:
        releaseVersion: ${{ steps.releaseversion.outputs.releaseVersion }}
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          # These can be stored in secrets, if desired.
          OPENSHIFT_USER: default
          OPENSHIFT_NAMESPACE: ssuganth-dev

        with:
          # URL to your OpenShift cluster.
          # Refer to Step 2.
          openshift_server_url: https://api.sandbox.x8i5.p1.openshiftapps.com:6443

          # Authentication Token. Can use username and password instead.
          # Refer to Step 3.
          openshift_token:        eyJhbGciOiJSUzI1NiIsImtpZCI6IlZ0UXdOWnhYbFNlUE50VEE5RngyelpEbkUxd0hoeHNhVXNCV1pWeW40YWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzc3VnYW50aC1kZXYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGVmYXVsdC10b2tlbi12cm10cyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiY2MwM2ExYTMtYjZmNy00YjAxLWFiMTQtZTUyMzc0MGJlYTdiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnNzdWdhbnRoLWRldjpkZWZhdWx0In0.URw3d6c-xf6gjrUZCl35wjAlV-MNnzDYEmNhG-xoPAdfU3DdODGLMCXTEkjDj0_yJ9L9gZb-PDEqdIKQEixaLzJfbZ2XWpZsZVlYkxyUU6HXdqrme4AK7fumsTR8FaKqiXFiMQvjv0ktkmsGyPb7LBAyS4roF6VE2MAQQhbJRk9JFVtbGkkSpRLEyBAa3IQYwTGxhSyCiyRalAdmjHbC-SRp3QElJCK3Wmbz5MY-4_S9jGVrxkVQADLT5EIJE6RYOeN16l4gMxKFylmyXngGWRaJCr5tisMVDvXkMm8Y3h7MZllsN0H3T3ZjASjakxf4nP4td3b9Y_hDnbbwVmoUlA

          # Optional - this sets your Kubernetes context's current namespace after logging in.
          namespace: ssuganth-dev
      
      - name: Get Release Version
        run: |
          branch=${GITHUB_REF}
          version=$(echo $branch | cut -d "/" -f2-)
          echo "releaseVersion=$version" >> $GITHUB_ENV
      
      - name: Print Release Version
        id: releaseversion
        run: |
          echo "Release version is ${{ env.releaseVersion }}"
          echo "::set-output name=releaseVersion::${{ env.releaseVersion }}"
          echo "Release Environment: ${{ github.event.inputs.environment }}"
      
      - name: POD Labelling
        env:
          releaseVersion: ${{ env.releaseVersion }}
        run: |
          oc label pods -l 'name=demoapi-dc' version=${releaseVersion} --overwrite
         
