name: Trigger deployment to test/prod Openshift environnment by Image stream re-tagging and labelling pod

on:        
    workflow_dispatch:
        inputs:
            app:
                description: 'App Name (jag-scss)'    
                required: true
            imageSourceEnv:
                description: 'Image Source Env'     
                required: true
                default: 'dev'
            imageTargetEnv:
                description: 'Target Release Env'
                required: true
jobs:
  oc-image-tagging:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.imageTargetEnv }}
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2
        
        # Get the version number which is prefixed with the Github release branches in format release/{version}
      - name: Get Release Version
        run: |
          branch=${GITHUB_REF##*/}
          version=$(echo $branch | cut -d "/" -f2-)
          echo "releaseVersion=$version" >> $GITHUB_ENV
      
      - name: Print Release Details
        run: |
          echo "Release version is ${{ env.releaseVersion }}"
          echo "Release Environment: ${{ github.event.inputs.environment }}"

        #Login to Openshift using OC SA and Token of respective env. for Pod labelling
      - name: Authenticate OC Env Specific SA
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: 17b24e-test
          OPENSHIFT_USER: deployer
        with:
          openshift_server_url: https://api.silver.devops.gov.bc.ca:6443
          openshift_token: eyJhbGciOiJSUzI1NiIsImtpZCI6InIxU0VzMHpBT1pXeEhSZVlxek14aXQ2R2FLUDF3RXprMlhHald5SFJaNzQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiIxN2IyNGUtdGVzdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZXBsb3llci10b2tlbi14ODI0NCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkZXBsb3llciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjgwZDdhYzRlLTQxM2YtNGNmZi1hMzcwLTY1OGZlNmRlNjE0YiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDoxN2IyNGUtdGVzdDpkZXBsb3llciJ9.CqhfoUnx8OfwkiXW9Lm2lmFOLBwbL5HiL-3PDOPn_Nu_F9NNpZxcNPLh0zQLNX2EvyrFH32F-ECNGk-RShcj0Klhs3MNQ1WXzA1NcuHfvaVYsSHhMjLmmjJuOwsCscF51shBY4gBzOqJV5oj51GU91v0hOHLZpX2PeX2pPERMe8F8RByvmtNQNF4VD7QZ2fTnEwbtpYM7w9CFUkblMXAgPudpVdWD9Q5t5sdM_G-rAUG165VmYrsZiXDyMtbsbs61guEjhIs2JY3VCc7lVbn_lXtVGt13t3SQJTvaPC6h8Iq_YE-zLTFZDMCJynx5yKj1QKfsthpxl0_7yRM7lYq9w
          namespace: 17b24e-test
        
        # Labels the pods with release version number for better identification.
      - name: Labelling Pod to release version
        env:
          releaseVersion: ${{ env.releaseVersion }}
          appName: ${{ github.event.inputs.app }}
          openshiftEnvNamespace: 17b24e-${{ github.event.inputs.imageTargetEnv }}
        run: |
          oc patch dc jag-scss --patch '{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"version\":\"V1\"}}}}}'
