name: Test OC Tagging

on:        
    workflow_dispatch:
        inputs:
            environment:
                description: 'Release Environment'     
                required: true
                default: 'dev'
jobs:
  oc-poc:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Login to Openshift
        run: |
          oc login --token=sha256~5aK4S8J9w5BA-6YEWcjC67iM7amEmHCqyYSw5CtAPUM --server=https://api.sandbox.x8i5.p1.openshiftapps.com:6443
      
      - name: Retag image to release env.
        run: |
          oc tag image-registry.openshift-image-registry.svc:5000/ssuganth-dev/redis:latest redis:v2
         
