name: Test OC Tagging

on:        
    workflow_dispatch:
        inputs:
            environment:
                description: 'Release Environment'     
                required: true
                default: 'dev'
jobs:
  oc-poc:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          # These can be stored in secrets, if desired.
          OPENSHIFT_USER: default
          OPENSHIFT_NAMESPACE: ssuganth-dev

        with:
          # URL to your OpenShift cluster.
          # Refer to Step 2.
          openshift_server_url: https://api.sandbox.x8i5.p1.openshiftapps.com:6443

          # Authentication Token. Can use username and password instead.
          # Refer to Step 3.
          openshift_token: sha256~xnl6UTXeIUEuqchGidfDi2oxLwJLfa4iBrgUCrJRzdY

          # Optional - this sets your Kubernetes context's current namespace after logging in.
          namespace: ssuganth-dev
      
      - name: Retag image to release env.
        run: |
          oc project ssuganth-dev
          oc tag image-registry.openshift-image-registry.svc:5000/ssuganth-dev/redis:latest redis:v2
      
      - name: End Openshift session
        run: |
          oc logout
         
