name: Test OC Tagging

on:        
    workflow_dispatch:
        inputs:
            environment:
                description: 'Release Environment'     
                required: true
                default: 'dev'
jobs:
  oc-poc:
    runs-on: ubuntu-20.04
    steps:

     - name: Sleep for 15 seconds
       uses: jakejarvis/wait-action@master
       with:
         time: '15s'
         
